ndlib/annex-ims

- .travis.yml
Enable container-based builds on Travis: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
Builds will start much more quickly, and it allows caching of gems between builds.
> Enable container-based builds on Travis

- spec/features/bins_spec.rb
- spec/features/item_to_shelf_spec.rb
- spec/features/items_spec.rb
- spec/features/trays_spec.rb
- spec/rails_helper.rb
- spec/services/associate_tray_with_item_barcode_spec.rb
- spec/services/item_path_spec.rb
- spec/services/item_restock_spec.rb
- spec/services/item_restock_to_tray_spec.rb
- spec/services/stock_item_spec.rb
- spec/support/api_url_helper.rb
Created spec helper to generate api urls based off the api configuration for the test environment.  This will prevent specs from breaking if the secrets.yml configuration is changed.
> More robust spec request stubbing

- app/services/destroy_item.rb
- app/services/get_item_from_barcode.rb
- app/services/log_activity.rb
- db/migrate/20150623185029_drop_activity_log_constraints.rb
- db/schema.rb
- spec/services/get_item_from_barcode_spec.rb
- spec/services/item_path_spec.rb
Why: Application was throwing an exception anytime the user tried to stock an item to tray with an invalid item.
How: An FK constraint on the ActivityLog model was preventing the stubbed out item from being deleted. Since the log should keep track of all changes, deletes included, I removed the constraints and updated the application to additionally create a log entry when an Item is deleted and when it is updated using data from the API.
> AIMS-209: Stock Items to Tray for invalid item throws error

- app/services/associate_shelf_with_item_barcode.rb
**WHAT** There was some redundant object creation in the AssociateShelfWithItem service class. It was running the association code whether or not the association already existed and this was duplicating work as well as activity logging. I added a test to avoid that duplication.
**HOW** The test checks whether the association already exists, and if so, simply restocks the item.
> AIMS-113 Reduce activity log insert to once per restock event

- app/views/trays/show_item.html.haml
Why: Currently, there is no way to differentiate between stocked, unstocked, and shipped items, and the Unstock button is always available even if an item has been shipped or already unstocked.
How: Added a status column to the form and changed the Unstock button to only appear when an item is stocked
> AIMS-200: Change handling of unstocked/shipped items in Items to Tray form

- app/models/api_response.rb
- app/services/api_get_item_metadata.rb
- app/services/api_get_request_list.rb
- app/services/api_handler.rb
- app/services/api_post_deliver_item.rb
- app/services/api_post_stock_item.rb
- app/services/external_rest_connection.rb
- app/services/get_item_from_barcode.rb
- app/services/sync_item_metadata.rb
- spec/features/items_spec.rb
- spec/fixtures/api/active_requests.json
- spec/fixtures/api/item_metadata.json
- spec/fixtures/api/scan_send.json
- spec/fixtures/api/stock_item.json
- spec/models/api_response_spec.rb
- spec/rails_helper.rb
- spec/services/api_get_item_metadata_spec.rb
- spec/services/api_get_request_list_spec.rb
- spec/services/api_handler_spec.rb
- spec/services/api_post_deliver_item_spec.rb
- spec/services/api_post_stock_item_spec.rb
- spec/services/get_item_from_barcode_spec.rb
- spec/services/sync_item_metadata_spec.rb
- spec/spec_helper.rb
- spec/support/api_helper.rb
This is some groundwork changes to the API calls that are needed before they can easily be moved to the background.  I didn't change any business logic as part of this pull request.
All API calls now return an ApiResponse which contains the status and the body of the response.  This response object can answer simple questions like whether the response was a success (200) or error.
The API handler will catch timeout errors and still return an ApiResponse.  Previously each API service was trapping their own timeout errors.
Disabled network request caching in the development and test environments.
Moved item metadata synchronization into its own service class.
Added specs for all API requests.
Updated the overall test suite order to be random, to help expose any test order dependencies.
> API refactoring

- app/jobs/sync_item_metadata_job.rb
- app/models/item.rb
- app/services/get_item_from_barcode.rb
- app/services/sync_item_metadata.rb
- app/workers/item_metadata_worker.rb
- db/migrate/20150625190556_add_item_metadata_status.rb
- db/schema.rb
- spec/jobs/sync_item_metadata_job_spec.rb
- spec/models/item_spec.rb
- spec/services/get_item_from_barcode_spec.rb
- spec/services/sync_item_metadata_spec.rb
- spec/spec_helper.rb
This is more groundwork for AIMS 212.
It adds a metadata status and timestamp which is used to determine if the item can be added to a tray.
> Aims 212 item metadata status

- app/controllers/requests_controller.rb
- app/models/request.rb
- app/services/api_remove_request.rb
- app/services/destroy_request.rb
- app/views/batches/index.html.haml
- config/routes.rb
- db/schema.rb
- spec/factories/requests.rb
- spec/features/bins_spec.rb
- spec/models/request_spec.rb
- spec/services/api_remove_request_spec.rb
- spec/services/destroy_request_spec.rb
- spec/support/api_helper.rb
**What** Added functionality to allow users to remove (delete) requests for various reasons
**Why** They needed a way to arbitrarily reject requests that could not be fulfilled at the Annex and bounce them back to either Hesburgh cataloging and circ, or ILL.
**How** I created two service classes; one to delete requests, and the other to interact with the API to archive the request so that it won't show up in the active request list until the request issue is resolved. I also modified the request model so that it will also delete any associated "match" records. The button on the index.html.haml page that lists requests now has a button on it that is in a form that points to the appropriate controller method. The button is also tied to a confirmation message to avoid accidental deletions. …
> Aims 181 remove request function

- app/models/item.rb
- app/services/get_item_from_barcode.rb
- app/services/sync_item_metadata.rb
- spec/features/item_to_shelf_spec.rb
- spec/features/items_spec.rb
- spec/features/trays_spec.rb
- spec/fixtures/api/item_metadata.json
- spec/services/item_path_spec.rb
- spec/services/item_restock_spec.rb
- spec/services/sync_item_metadata_spec.rb
Why: The user needs to be notified immediately that the item should not be trayed if the sublibrary code is not marked for Annex.
How: SyncItemMetadata can now test for errors in the data even if the query is successful. When an item is not marked for annex, it will return a not_for_annex error which will trickle up to the user as an immediate "Item # not found" error.
NOTE: After merging this, you will no longer be able to pull books from the shelf for test data. You will need to find barcodes that have sublibrary codes of "ANNEX"
> AIMS-221: Change IMS to return error if sublibrary != "Annex"

- app/assets/stylesheets/framework_and_overrides.css.scss
- app/views/trays/show_item.html.haml
- config/locales/en.yml
- spec/factories/items.rb
- spec/services/sync_item_metadata_spec.rb
AIMS-231 - If an item that hasn't successfully synced with the API is stocked onto a tray, we need to display the status.
This will display the status of the metadata sync, and will highlight the row if it's not found or not for the annex.
> AIMS-231 Show the metadata status of an item if it failed to load

- app/jobs/api_stock_item_job.rb
- app/services/api_post_stock_item.rb
- app/services/stock_item.rb
- app/workers/api_worker.rb
- lib/tasks/sneakers.rake
- spec/jobs/api_stock_item_job_spec.rb
- spec/services/api_post_stock_item_spec.rb
- spec/services/stock_item_spec.rb
- spec/workers/api_worker_spec.rb
This adds an additional worker for processing non-metadata jobs, and it moves the ApiPostStockItem service to the background
> AIMS-213 run the stock item api request in the background.

- app/views/shelves/show.html.haml
Why: In Item Direct to Shelf, when unstocking an item there is no feedback to the user that the item is now unstocked, and the unstock button is still available.
How: 
-Added status code to the item list
-Changed the unstock button to only be shown when the status of the item is 'stocked'
> AIMS-237: Hide unstock for unstocked items in Item->Shelf

- app/services/destroy_request.rb
**WHAT** Bug fix to compensate for requests not attached to an item via barcode
**WHY** Request deletion needs to be logged even before an item match has been found
**HOW** I changed the destroy method so that it makes a clone of the request object, which is otherwise frozen, and sets the barcode to equal the trans value, which is a more reliable identifier for requests anyway.
> AIMS-181 Bug fix for logging requests that don't have an item barcode

- Gemfile
- config/application.rb
Our deploy server needs to install whenever in order to update the cron tasks on deploy.
Moving most of our gems to the "application" group will allow the deploy server to exclude that group during bundle install using `bundle install --deployment --without application development test`
> Deploy fix

- .travis.yml
- app/controllers/bins_controller.rb
- app/jobs/api_scan_send_job.rb
- app/jobs/api_stock_item_job.rb
- app/models/batch.rb
- app/services/api_post_deliver_item.rb
- app/services/process_match.rb
- app/services/scan_item.rb
- app/views/batches/retrieve.html.haml
- config/sunspot.yml
- db/seeds.rb
- spec/jobs/api_scan_send_job_spec.rb
- spec/models/batch_spec.rb
- spec/services/api_post_deliver_item_spec.rb
- spec/services/process_match_spec.rb
- spec/services/scan_item_spec.rb
- spec/services/ship_item_spec.rb
This moves the scan/send API requests to a background job.
Other changes include:
Moved match processing out of the bin controller and into a service class.
Fixed a bug where batch retrieval failed when there isn't a tray and shelf associated with an item.
Move sunspot to a different port to avoid conflicting with other local solr instances.
> AIMS-215 move send/scan API requests to the background

- app/services/sync_item_metadata.rb
- spec/services/sync_item_metadata_spec.rb
The item metadata jobs were not being requeued on failure.  In order to be requeued, an exception needs to be raised.
> Requeue item sync job in background

- app/services/build_request_data.rb
- app/views/batches/index.html.haml
- db/schema.rb
**What**: Enhanced item display on batch creation page to show messages based on item status, and prevent selection of item that is "unstocked" or "shipped"
**Why**: To prevent users from selecting items that are not on the shelf, but also give them information about the item status.
**How**: Modified index.html.haml page to include conditional logic based on item status (which is driven by javascript), and modified the build_request_data service class so that item metadata includes the status information.
> Aims 197 batch creation item status

- app/controllers/requests_controller.rb
- app/services/activity_logger.rb
- app/services/api_remove_request.rb
- app/views/batches/index.html.haml
- config/routes.rb
- spec/services/activity_logger_spec.rb
- spec/services/api_remove_request_spec.rb
There was a bug with removing the first request in the batch list, which was caused by nested forms.  This using the link_to method to avoid creating a form.
Also adds logging of the api remove request call for AIMS-248.
> Fix a bug with removing a request (problem with nested forms), 

- app/models/issue.rb
- app/services/activity_logger.rb
- app/services/add_issue.rb
- app/services/sync_item_metadata.rb
- app/views/items/issues.html.haml
- config/locales/en.yml
- db/migrate/20150706191200_delete_existing_issues.rb
- db/migrate/20150706191210_add_issue_type_to_issues.rb
- db/schema.rb
- spec/factories/issues.rb
- spec/services/activity_logger_spec.rb
- spec/services/add_issue_spec.rb
- spec/services/sync_item_metadata_spec.rb
Currently issues are being added every time a metadata API error is encountered.  The following changes are a part of this pull request:
1) Rather than store a full message, store an issue_type value (i.e. not_found, not_for_annex)
2) Items should only have issues generated for the metadata statuses of "not_found" and "not_for_annex".  Remove the other AddIssue calls
3) If an open issues already exists for a given barcode and issue_type, do not add a new issue.
> AIMS-233 update item issues

- .travis.yml
- spec/features/batches_spec.rb
- spec/features/search_spec.rb
- spec/services/build_batch_spec.rb
- spec/spec_helper.rb
- spec/support/solr_spec_helper.rb
- spec/support/sunspot.rb
We only need the truncation database cleaner strategy for examples that use the Capybara js driver.  The change to spec_helper `if example.metadata[:js]` cuts off several seconds.
I also added a check to the solr spec helper to monitor the status of the test instance.  That cuts off a couple seconds for the full suite as well.
> Spec performance improvements

- app/controllers/batches_controller.rb
- app/services/activity_logger.rb
- spec/controllers/batches_controller_spec.rb
- spec/services/activity_logger_spec.rb
Why: Need to track when an item has been skipped during batch processing
How: Added a skip_item method to ActivityLogger and updated BatchesController to call it when an item is skipped.
> AIMS-251: Add SkippedItem to ActivityLog

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/framework_and_overrides.css.scss
- app/controllers/batches_controller.rb
- app/controllers/items_controller.rb
- app/controllers/requests_controller.rb
- app/controllers/shelves_controller.rb
- app/controllers/trays_controller.rb
- app/services/api_get_request_list.rb
- app/services/associate_shelf_with_item_barcode.rb
- app/services/associate_tray_with_item_barcode.rb
- app/services/get_item_from_barcode.rb
- app/services/get_requests.rb
- app/services/item_path.rb
- app/views/batches/index.html.haml
- config/locales/en.yml
- config/routes.rb
- config/schedule.rb
- lib/tasks/annex.rake
- spec/features/trays_spec.rb
- spec/services/api_get_request_list_spec.rb
- spec/services/associate_tray_with_item_barcode_spec.rb
- spec/services/get_item_from_barcode_spec.rb
- spec/services/get_requests_spec.rb
This removes the API call every time the batches index page is visited.
The API call is moved to a cron job that runs every 15 minutes, and can be manually triggered by clicking a new "Refresh" button.
Also updated bootstrap-sass and sass-rails to fix the glyphicons.
I also refactored the GetItemFromBarcode calls to use named parameters, which I ended up not needing, but I didn't want to make the change and not commit it.
> AIMS-165 add a cron job for retrieving requests

- app/services/unstock_item.rb
- spec/services/unstock_item_spec.rb
Why: Adding an item to a bin currently calls UnstockItem, which will changed the status of the item and log an UnstockedItem activity. This can happen whether the Item was associated with a tray or not. If an item is not yet associated with a tray, we don't want it to log an UnstockedItem activity.
How: Changed UnstockedItem to not log if it does not have an associated tray.
> AIMS-262: Don't log UnstockedItem if an item is not associated to a tray

- app/controllers/batches_controller.rb
- app/services/activity_logger.rb
- spec/controllers/batches_controller_spec.rb
- spec/services/activity_logger_spec.rb
Why: Need to track when an item has been accepted during batch processing
How: Added an accept_item method to ActivityLogger and updated BatchesController to call it when an item is accepted.
> AIMS-250: Add AcceptedItem to ActivityLog

- app/controllers/batches_controller.rb
- spec/controllers/batches_controller_spec.rb
Why: There is more than one area where an item can be skipped. Missed this on the first PR.
How: Added a log call to the scan_bin method when the user skips the item.
> AIMS-251: Log SkippedItem

- Gemfile
- Gemfile.lock
So the Rails logger during development is not as cluttered with
asset chatter.
More information: https://github.com/evrone/quiet_assets
$ bundle
> Adding quiet_assets

- app/models/request.rb
- app/queries/request_query.rb
- app/services/activity_logger.rb
- app/services/complete_request.rb
- app/services/process_match.rb
- db/migrate/20150708181811_add_status_to_requests.rb
- db/schema.rb
- spec/models/request_spec.rb
- spec/queries/request_query_spec.rb
- spec/services/activity_logger_spec.rb
- spec/services/complete_request_spec.rb
- spec/services/process_match_spec.rb
Why: Need to log an activity when a request has been filled
How: Anytime a match gets processed, it will now change the status of the match to completed and additionally check to see if there are any remaining matches left for the associated request. If there are none, it will flag the request as completed and log a FilledRequest record to the ActivityLogs.
> AIMS-252: Log FilledRequest

- CODE_OF_CONDUCT.md
Given that this is being released as open source, and perhaps
accepting non-Notre Dame contributions, we should explain our
expected code of conduct.
This is a copy of the Code of Conduct from
[Sipity](https://github.com/ndlib/sipity) which in turn is an
adaption of the [Contributor Covenant](http:contributor-covenant.org)
[skip ci]
> Adding code of conduct to the project

- app/services/is_bin_barcode.rb
- app/services/is_item_barcode.rb
- app/services/is_object_item.rb
- app/services/is_object_shelf.rb
- app/services/is_object_tray.rb
- app/services/is_shelf_barcode.rb
- app/services/is_tray_barcode.rb
- app/services/is_valid_thickness.rb
@bcad4475c9b1e82f7d2dbbdd6a9e8cc182c50288
Freezing strings that are regularly reused
The strings were being instantiated and regularly collected via
GC. Prefer that they be instantiated once.
See for additional details http://josephyi.com/freeze/
@7258ee0699af9a6ceaf8c2466c7e9e653512546c
Prefer module functions instead of objects
The app/services/is_*.rb group of objects were instantiating an object
with each call to these "simple" service objects. This instantation had
two effects:
1) Another object that would need to be garbage collected
2) Additional steps to perform a "simple" comparison
This implementation preserves the outward facing interface of the Is*
objects, reduces memory consumption and GC, and still leaves room for
leveraging full objects if the logic gets more complicated.
> Compress to module function

- app/services/is_item_barcode.rb
- spec/services/is_item_barcode_spec.rb
This is an interesting question, is '' an ItemBarcode?
If "" is a valid ItemBarCode then an ActiveRecord::InvalidRecord
exception is thrown on this line:
https://github.com/ndlib/annex-ims/blob/5d5e303e5fb6d4faa55157f593fc9feda78ff863/app/services/get_item_from_barcode.rb#L35
If "" is not a valid ItemBarCode then a StandardError exception is
thrown.
https://github.com/ndlib/annex-ims/blob/5d5e303e5fb6d4faa55157f593fc9feda78ff863/app/services/get_item_from_barcode.rb#L21
It is important to decide what is the correct answer as we the
handling of [AIMS-271](https://jira.library.nd.edu/browse/AIMS-271)
will vary
> Asserting that '' is not a ItemBarcode

- app/services/search_items.rb
Using OpenStruct invalidate's Ruby's method cache.
https://github.com/charliesome/charlie.bz/blob/master/posts/things-that-clear-rubys-method-cache.md
> Removing OpenStruct usage

- app/models/batch.rb
- app/services/activity_logger.rb
- app/services/build_batch.rb
- spec/services/activity_logger_spec.rb
- spec/services/build_batch_spec.rb
Why: Need to track anytime a request is batched
How: Modified BuildBatch to log an activity for each unique request associated with the batch (since a batch can have multiple items for one request). To do this I had to modify the association between Batch and Request to only include unique values since it's through a 1->many relationship with Match
> AIMS-255: Log BatchedRequest

- Gemfile.lock
- app/services/activity_logger.rb
- app/services/build_batch.rb
- spec/services/activity_logger_spec.rb
- spec/services/build_batch_spec.rb
Why: Need to track when an item is matched
How: Added a match_item log method and changed BuildBatch to log a MatchedItem for each item added to matches.
> AIMS-256: Log MatchedItem

- app/services/scan_item.rb
- app/services/unstock_item.rb
- spec/services/scan_item_spec.rb
- spec/services/unstock_item_spec.rb
Why: For item scans, we are getting an extra UnstockedItem message in the log when the request is completed.
How: ScanItem was calling an extra UnstockItem. At this point it should be unstocked, so I removed the call. Also changed UnstockItem to not perform the update to the object or log the call if the item was already unstocked.
> AIMS-270: UnstockedItem message when fullfilling a request

- app/controllers/trays_controller.rb
This is not an ideal solution, but instead addresses the issue
where not providing a Barcode for the /trays/items page throws an
exception.
Closes AIMS-271
> AIMS-271: Handle an exception due to data validation

- app/views/items/issues.html.haml
- db/seeds.rb
Why: A new barcode search field was added, but we already had a search field that allowed searching by barcode. 
How: Removed the added field and gave focus to the existing Search input. Also added seed data for the issues table
> AIMS-234: Autofocus on Search within Items with Issues

- app/services/activity_logger.rb
- app/services/add_issue.rb
- app/services/sync_item_metadata.rb
- spec/services/activity_logger_spec.rb
- spec/services/add_issue_spec.rb
- spec/services/sync_item_metadata_spec.rb
The user was not getting logged when an issue was added.  This can help in identifying who scanned the barcode that has the issue.
> Log the user when adding an issue

- app/views/trays/show_item.html.haml
Why: We want to remove this button to prevent accidents
How: Temporarily commented this out in the code.
> Remove unstock button temporarily

- Gemfile
- Gemfile.lock
- app/services/api_get_request_list.rb
- app/services/api_post_deliver_item.rb
- app/services/api_post_stock_item.rb
- app/services/external_rest_connection.rb
- app/services/notify_error.rb
- lib/tasks/sneakers.rake
- spec/services/external_rest_connection_spec.rb
- spec/services/notify_error_spec.rb
- spec/support/api_helper.rb
Removing Typhoeus in favor of Net HTTP since Typhoeus was causing issues with process forking.
Move sneakers rake methods into helper class to avoid global method definitions
Only include the api response attributes in api errors to allow some grouping of error messages for each item
Disable any request caching to prevent receiving stale data from the API server
Use TERM instead of INT to kill running sneakers processes (INT could detach processes rather than stop them depending on the configuration)
> AIMS-288 Fix sneakers restart while jobs are in the queue

- app/controllers/items_controller.rb
- app/controllers/shelves_controller.rb
- app/controllers/trays_controller.rb
- app/services/api_handler.rb
- app/services/notify_error.rb
- app/workers/retry_worker.rb
- config/environments/staging.rb
- lib/tasks/annex.rake
- lib/tasks/sneakers.rake
- spec/controllers/trays_controller_spec.rb
- spec/services/api_handler_spec.rb
- spec/services/notify_error_spec.rb
- spec/workers/retry_worker_spec.rb
This includes a number of changes to notifications sent through Airbrake.
1.Calls using our NotifyError service don't have access to the controller params and environment.  Using the notify_airbrake method provided by the Airbrake gem allows us to send more information.
2. I updated the rake tasks to make use of Airbrake's internal handler for errors in rake tasks
3. I enhanced the NotifyError service to send more information (similar to how Airbrake handle's rake tasks)
4. Improved a handful of related specs
5. Updated the staging environment to match prod/pprd configurations so it will send error messages.
> Improve quality of error information sent via Airbrake

- Gemfile.lock
- app/services/api_handler.rb
- app/services/api_post_stock_item.rb
- app/services/external_rest_connection.rb
- spec/services/api_handler_spec.rb
- spec/services/external_rest_connection_spec.rb
What: Added return message body for 422 return codes
Why: So that we can see the error message returned from Aleph in the activity log
How: Modified the external rest class so that it includes message bodies for that return code
> AIMS-295 Add message body for 422 return codes

- app/models/issue.rb
- app/services/add_issue.rb
- app/services/api_post_stock_item.rb
- app/views/items/issues.html.haml
- config/locales/en.yml
- db/migrate/20150728200747_drop_issue_user_fk_add_message.rb
- db/schema.rb
- spec/services/add_issue_spec.rb
- spec/services/api_post_stock_item_spec.rb
Why: Whenever we get a 422 back from the api when stocking an item, it means that aleph encountered an error with processing/updating the item. This needs to bubble up to the user as an issue so that someone can manually address the problem in Aleph.
How: Created a new aleph_error type in issues and started creating an issue when we receive a 422 during ApiPostStockItem. The api will now respond with the error message that it received from aleph, so added this to issues table/form. We also decided to drop the fk constraint and user_id validation on issues. Issues previously required an associated user, but background operations do not have a user.
> AIMS-295:  Add 422 issue

- app/queries/activity_log_query.rb
- db/migrate/20150814204601_add_item_tray_barcode_index.rb
- db/schema.rb
Why: Item/shelf detail report is extremely slow.
How: Analyzed the query that this report uses and found that adding an index on data->item->barcode and data->shelf->barcode will speed up the query substantially. Added these indices and changed the query to use the ? operator to make use of the indices.
> AIMS-303: Activity indexing

- app/views/items/issues.html.haml
AIMS-299: Adjustments to the display issues table to limit text wrapping:
1. Removed the "Message" column, and if the message is present, display it under the type
2. Limit the width of the barcode column
AIMS-281: Fixed created date sorting
1. Added a hidden timestamp column to use as sorting data for the Created column
2. Barcode sorting appears to be working just fine.
> AIMS-299, AIMS-281 improve items with issues table

- app/services/get_requests.rb
Why: The requested date does not reflect when the request was actually created.
How: Changed the requested field to use the request_date_time received from the api instead of todays date.
> AIMS-317: Request date not showing correct date

- app/views/search/index.html.haml
Why: To simplify usage with the scanner
How: Added autofocus to the criteria box on item search.
> AIMS-310: Autofocus on search criteria to make scanner easier to use

- app/assets/stylesheets/framework_and_overrides.css.scss
- app/views/items/show.html.haml
- spec/features/items_spec.rb
Why: When scanning an item in directed put away, the info appears at the bottom. The screen on the scanner is fairly small, and this info gets cut off. Reworked the layout of this form to make all needed info visible.
How: Had to remove a label, move the info to the top, and make the paragraphs a little more compact in order to accommodate for the info, inputs, and error message.
> AIMS-315: Directed put away info not visible

- app/views/items/issues.html.haml
Datatables has built-in support for saving the state of the table via local storage.  This saves it for a short time (5 minutes), so if the user leaves the page and then comes back, the table will be in the state that it was in when they left the page.
> AIMS-300 save the state of the issues table

- app/services/build_request_data.rb
- app/services/search_items.rb
- app/views/batches/index.html.haml
- spec/services/build_request_data_spec.rb
- spec/spec_helper.rb
Why: If a request has many items that match, it does not show all items that it should.
How: Changed to retrieve 5,000 items per page instead of 50. There is still no way to go to next page of items (without a redesign), so if there are more than 5k items (more than one page) it will send an error message in with the hash of item data. The js that processes this will now print the error to the user to notify them that the request is likely bad.
Example:
> AIMS-318: Too many items for a request

- app/services/get_requests.rb
- db/migrate/20150901194225_add_patron_fields_to_requests.rb
- db/schema.rb
- spec/services/get_requests_spec.rb
What: They want to be able to do reporting on requests using the patron status (Grad/Undergrad), patron institution, patron department, and pickup location for requests.
I added four new fields to the request table and set their values from the data returned by the API.
I also need the `AIMS-319-request-patron-info` branch reviewed on the API repository.
> AIMS-319 Track pickup location, patron institution, department, and status

- app/controllers/batches_controller.rb
- app/services/activity_logger.rb
- spec/controllers/batches_controller_spec.rb
- spec/services/activity_logger_spec.rb
Why: If a user removes a match on the "View Current Batch" screen, it is not logging the activity and we need it for reporting
How: Added a RemovedMatch activity log and modified batches controller to log this activity any time the user removes a matched item from a batch.
> AIMS-272: Log activity when removing a match

- app/controllers/batches_controller.rb
- app/services/accept_match.rb
What: Disabled the automatic skip of remaining items in a batch for a request so that multiple items can be selected to fulfill a request
How: Commented out four lines of code in the AcceptMatch service class
> AIMS-243 Commented out code to skip remaining items in request

- app/services/get_requests.rb
- spec/services/get_requests_spec.rb
Currently when requests are loaded from the API, an error on an individual request will break the entire process and will not provide any helpful debugging information.
This adds error handling around individual request processing so an error will not stop the entire process.
> AIMS-322 error handling and debugging for requests sync

- app/assets/stylesheets/batches.css.scss
- app/views/batches/index.html.haml
I perhaps went overboard in exploring this...
1. Indent the item list row slightly
2. Make sure the child row has the same background color as the parent row
3. Left align the search box
4. Conditionally show the search box and pagination if there are enough records.
5. Default to sorting by chron, added some hopefully intelligent sorting on chron so it sorts numerically rather than by string value
Example with filtering:
Example without filtering:
> Batch items results list styles and enhancements

- app/services/build_request_data.rb
- app/services/search_items.rb
- spec/services/build_request_data_spec.rb
- spec/services/search_items_spec.rb
When we increased the hardcoded limit in SearchItems to 5,000, it increased the number of results being displayed on the item search page to that amount.
This reverts the default back to 50, and updates the BuildRequestData service to request 5,000 per page.
I also added a spec for the SearchItems service so we have complete coverage on that file.
> AIMS-324 configurable item search per page

- app/views/batches/index.html.haml
Why: User would like to additionally be able to filter the items that match a request.
How: Each sub table will now use DataTables. I also had to modify the way that the global request filters work since these are applied to all datatables, not just specific instances.
> AIMS-321: Batch items filter

- app/controllers/application_controller.rb
- app/controllers/simple_cas_controller.rb
- app/services/is_user_session_expired.rb
- app/views/layouts/_navigation.html.haml
- app/views/users/timed_out.html.haml
- config/environments/development.rb
- config/environments/pre_production.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
- db/migrate/20150904181322_add_users_last_activity.rb
- db/schema.rb
- spec/controllers/application_controller_spec.rb
- spec/factories/users.rb
- spec/services/is_user_session_expired_spec.rb
Why: User sessions remain valid for indefinite amount of time, causing security issues.
How:  User sessions will now expire. Did not use built in devise timeoutable method since it doesn't allow customizing the timed out page. Created our own expiration calculation which will now render a timed out page that forces the user to click login. By default, will timeout after 10 hours of inactivity for prod/preprod/staging. This should cause a login once per day if they're active in it all day. For dev using 24 hours. These can be changed in configs.
> AIMS-325: Session timeout

- app/views/bins/show.html.haml
- app/views/welcome/index.html.haml
Why: Now that they are able to process requests directly in the Annex, they need more information on the request to be displayed when processing a bin.
How: Added Article Title and Description. Description is a packed field that contains things like pages, volume, etc. We also decided to change "Process Batch" to "Process Bin". The view linked to by "Process Batch" is actually showing a list of bins. The desired behavior for the workflow is to show all bins, not just the bins associated with that user's current batch. So we're renaming the menu option to match so that there's less confusion for future users/devs.
> AIMS-336: Add process details

- app/controllers/bins_controller.rb
- app/services/process_match.rb
- app/views/bins/show.html.haml
- lib/tasks/annex.rake
- spec/controllers/bins_controller_spec.rb
- spec/services/process_match_spec.rb
Why: If multiple scan requests for a single item would get batched, the user would only be able to process one of them.
How: The application was immediately dissociating an item from a bin as soon as the first scan was processed, which prevented the view from showing the remaining matches. Changed the app to only dissociate an item from a bin once all requests in that bin for that item have been fulfilled. Now, when they process one request, it will flash a message warning that there are remaining requests for that item. In addition, I created a rake task that we can use to spot check and clean up the data when we deploy.
> AIMS-331:  Empty batch bug

- app/services/destroy_item.rb
- lib/tasks/annex.rake
- lib/tasks/services/destroy_invalid_items.rb
- spec/services/destroy_item_spec.rb
Why: A lot of items have been added to the system using junk data from the barcode scanner due to the way we optimistically create an item, then look up its info later. This is getting in the way of querying/viewing valid items.
How: Created a rake task to destroy all items that are not assigned to a tray and are either "not found" or "not marked for annex". This task will be run adhoc to clean up the data (such as during our next deploy). Future development such as input validation should begin to prevent this data from being created, so a cron job is likely not needed, but if we do end up creating one, it can just use this rake task.
> AIMS-219: Cleanup "not found" items that are not associated with a tray

- app/models/item.rb
- app/presenters/item_view_presenter.rb
- app/views/items/item_detail.html.haml
- spec/presenters/item_view_presenter_spec.rb
What: Added information to the item detail page that indicates the current location of the item.
Why: It had been difficult to determine the current status of an item if it had been retrieved for batch processing and was sitting in a bin awaiting processing, having been shipped, or having returned from a loan awaiting restocking. This information will help to alleviate that problem.
How: Created a new method in the item view presenter that returns location strings and added that information to the item detail view.
> Aims 340 add bin info to item details

- app/views/bins/show.html.haml
Changing appearance of the remove button. Will now say Skip and look like the Skip button used in batch retrieval. It's a similar operation that the user is familiar with, so they should better understand what this action will do at this point in the workflow.
> AIMS-263: Remove item from bin

- app/controllers/users_controller.rb
- app/services/get_user_type.rb
- app/views/users/index.html.haml
- spec/controllers/users_controller_spec.rb
- spec/services/get_user_type_spec.rb
Admins can now update the type of user for existing users in the database via the users page, which now has select options for user types and update button. Every time the user type is changed, there will be a notification on top of the page that will give details of the update. Also the current user is disabled to change own user type due to a safety requirement.
> Updates for users page AIMS-335

- app/controllers/trays_controller.rb
- app/views/trays/count_item.html.haml
- app/views/trays/show_item.html.haml
- config/locales/en.yml
- config/routes.rb
- spec/features/trays_spec.rb
When a tray is full the user clicks "Done".  At that point the user is prompted to "Enter the number of items in the tray."
If the count matches, the user is taken to the Stocking page to scan the next Tray.
If the count does NOT match, the user receives an error message and is prompted to recount, and enter the count again.
> AIMS-354: Added validation for count of items in the tray

- app/services/search_items.rb
- app/views/search/index.html.haml
- spec/features/search_spec.rb
- spec/services/search_items_spec.rb
The search will now, by default, wrap the query in * to find anything that contains the criteria given. The ticket was written from the perspective of searching bib numbers, but I can't imagine we wouldn't expect this behavior on all fields. If we do need to ever query for exact matches, we can pass an exact_match=true param and it will not wrap the query in *. At the moment, I don't have this as an input anywhere on the form because I wasn't sure if this would really be needed. Trying to keep the form simple, but if we find we need it, it will be simple to add a checkbox to do an exact match.
> As a user on Item Search I can search for a Bib number with or without entering the leading zeros

- app/controllers/batches_controller.rb
- app/views/batches/bin.html.haml
- app/views/batches/retrieve.html.haml
- spec/controllers/batches_controller_spec.rb
Problem was due to the usage of Batch.current_match. It made an assumption about which match should be modified when posting back data. If the user clicked on it multiple times, such as in the case of an impatient user clicking the button again before receiving a response, it would receive all of the requests and cause each match in order to be accepted, without the user being aware. Changed it to expect the form to post the match id as a param so that it's explicitly modifying the correct match. 
This also affected the form that requires the user to accept an item by scanning it. It was possible to skip multiple items without realizing it. Fixed this as well.
> Bugfix: The IMS will sometimes assign an item from a batch to a bin, without the user scanning its barcode in the UI

- app/views/batches/index.html.haml
The need was to persist the search filters between page refreshes when the user is creating a batch. I added two callbacks to save, and subsequently load state for custom filter params. The save callback puts the custom filter params into state which is saved locally for the browser. The load callback restores the form controls to the saved state. State is saved / loaded when the form controls are changed. I also added a function that injects a (much needed, IMHO) state load function that can be called as needed.
> AIMS-320 Add functions to preserve batch search filters

- app/controllers/trays_controller.rb
- spec/features/batch_retrieval_spec.rb
- spec/features/batches_spec.rb
- spec/features/bins_spec.rb
- spec/features/item_to_shelf_spec.rb
- spec/features/items_spec.rb
- spec/features/search_spec.rb
- spec/features/shelves_spec.rb
- spec/features/trays_spec.rb
- spec/features/view_active_batches_spec.rb
- spec/features/view_processed_batches_spec.rb
- spec/support/authentication_helper.rb
Admin users should not have to count the items as an additional QC step when stocking an item to a tray. 
Changed the count_items to redirect to the trays/items path when the user is an admin
> As an Admin user I do not have to do Tray QC

- app/assets/stylesheets/framework_and_overrides.css.scss
- app/controllers/trays_controller.rb
- app/models/issue.rb
- app/views/trays/check_items.html.haml
- app/views/trays/check_items_new.html.haml
- app/views/welcome/index.html.haml
- config/locales/en.yml
- config/routes.rb
- spec/controllers/trays_controller_spec.rb
Adds a Quality Control menu that allows the user to scan a tray, then scan each item in the tray to make sure the associated items in the system match the items in the physical tray. This does not persist any information about the QC session in the database, so it relies on the view to persist previous scan data. This may change in the future when this becomes part of a workflow, but for now this seems like the simplest approach until we know what that looks like.
> As a user I can QC the items in a Tray

- app/controllers/items_controller.rb
- app/queries/activity_log_query.rb
- app/services/activity_logger.rb
- app/services/resolve_issue.rb
- spec/features/items_spec.rb
- spec/services/activity_logger_spec.rb
- spec/services/resolve_issue_spec.rb
Its hard to see what's happening to these items in order to identify a pattern since the reports don't show when the issues were resolved (without going into psql and manually querying). Made a few changes to make this easier in the future:
- Added the ResolvedIssue action type to the report for an item.
- Logging of ResolvedIssue action for items is inconsistent with the way other logs are produced. All others expect the associated item to be logged with the action. Changed to require an item when creating a log of this type. Unfortunately, this won't retroactively change logs that are there, so I had to also modify the query to also check if the issue had the item barcode.
> Items with Issues that won't go away

- app/controllers/deaccessioning_controller.rb
Unstocked is not the same as not stocked. There's also shipped.
> AIMS-403 If not stocked.

- app/views/deaccessioning/index.html.haml
- app/views/shared/_search_form.html.haml
The button was tied to the wrong form. Where it was, it would never create a request, as it was submitting to the wrong method.
> Quick bugfix to move button to the right form.

- README.md
- app/queries/activity_log_query.rb
- app/views/items/item_detail.html.haml
When the full tray object is not stored in the activity log, the valid tray label was not appearing in the item detail view history. This is a fix for that - added a utility method on the query log class to determine what the label should be no matter what is stored in the activity log
> Fix for tray labels in item detail view

- app/models/item.rb
- app/services/search_items.rb
- spec/services/search_items_spec.rb
It may be necessary to do `bundle exec rake sunspot:reindex` after this change is deployed. I've never been able to test Solr with rspec, but this works locally.
I added this to "bin" in addition to trays and shelves because even though bin is not listed in search, we do index on it, so we might want to search on it later.
> AIMS-466 ignore hyphens

- app/controllers/shelves_controller.rb
- app/controllers/trays_controller.rb
This should resolve the error with an empty error bar showing up on the quality control pages. I also noticed errors persisting past clicking 'done', so I took care of that, too.
> Fix the blank error bar in quality check pages

- Gemfile
- Gemfile.lock
- config/deploy.rb
This got updated along with the other gems. There don't look to be any breaking changes, so I'm updating the locked version accordingly.
> Update capistrano lock version to match gem.

- config/deploy.rb
Setting this value to true allows for the correct exit status to be returned when running capistrano with SShKit - we need to set this so that Jenkins deploys don't hang indefinitely
> Set PTY to true to fix exit status code issue
