ndlib/annex-ims

app/views/batches/index.html.haml
app/views/trays/show.html.haml
db/migrate/20150520165509_add_del_type_to_request.rb
db/schema.rb

**WHAT** Bug fix for duplicate log entries when tray is reshelved
**HOW** Updated index haml file to include a conditional and only call the reshelving service to avoid duplicate log entries.

Aims 113 fix logging bug for reshelving trays

---

Gemfile
Gemfile.lock
README.md
app/controllers/trays_controller.rb
app/views/search/index.html.haml
spec/features/batches_spec.rb
spec/features/bins_spec.rb
spec/features/item_to_shelf_spec.rb
spec/features/items_spec.rb
spec/features/search_spec.rb
spec/features/trays_spec.rb
spec/services/associate_tray_with_item_barcode_spec.rb
spec/services/item_path_spec.rb
spec/services/item_restock_spec.rb
spec/services/item_restock_to_tray_spec.rb
spec/services/stock_item_spec.rb
spec/spec_helper.rb

**WHAT** Corrected many feature and unit tests so that they are better isolated and include better mocking and stubbing to avoid external API calls. Also did some minor code corrections and enhancements to account for some regression issues.
**HOW** Several tests were rewritten, and some minor corrections to certain classes and views were included. Making more use of Capybara for feature testing, as well as webmock. I didn't remove the dependency on FactoryGirl, but I would suggest we do that in the future because it's problematic.

Aims 208 fix unit and feature tests

---

.hound.yml
Gemfile
Gemfile.lock
app/services/notify_error.rb
app/workers/item_metadata_worker.rb
app/workers/retry_worker.rb
config/application.rb
config/deploy.rb
config/environments/test.rb
config/initializers/sneakers.rb
config/secrets.yml.travis
config/style_guides/.javascript-style.json
config/style_guides/.ruby-style.yml
lib/tasks/sneakers.rake
spec/workers/item_metadata_worker_spec.rb
spec/workers/retry_worker_spec.rb

This is just initial infrastructure to start moving jobs to background processes.

Adding basic sneakers support, created initial worker

---

app/views/welcome/index.html.haml

**WHAT** Changed some of the top level menu options
**WHY** At the request of Aaron and Miranda
**HOW** Updated the index haml file at the top level view

AIMS-207 Change and reorder several menu options

---

app/services/api_get_request_list.rb
app/services/get_requests.rb
spec/services/api_get_request_list_spec.rb

The API refactoring introduced a bug in GetRequests.  This resolves that error.

Fixed active requests retrieval

---

app/controllers/application_controller.rb
app/controllers/batches_controller.rb
app/controllers/bins_controller.rb
app/controllers/items_controller.rb
app/controllers/search_controller.rb
app/controllers/shelves_controller.rb
app/controllers/simple_cas_controller.rb
app/controllers/trays_controller.rb
config/routes.rb
spec/controllers/welcome_controller_spec.rb

Why: User was getting a login required message after successfully logging in.
How: Eliminated the flash message by requiring the user to always login before trying any actions

AIMS-168: Remove login message

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/schedule.rb
lib/tasks/sneakers.rake
spec/support/authentication_helper.rb

This adds a scheduled task (using the whenever gem) to ensure that the sneakers workers are running on the server.  It checks that the pid file is present and that the specified process id is running.

Aims 228 Add a scheduled task to ensure sneakers is running

---

config/deploy/pre_production.rb
config/environments/pre_production.rb

Added deploy configuration for the pprd environment

Aims 225 deploy config for pprd

---

config/deploy/production.rb

This is the deploy config for the production environment

AIMS-239 AIMS-225 Prod deploy config

---

app/views/batches/retrieve.html.haml

**What**: Added request description to batch retrieval items
**How**: Modified the HAML to include the field, and added field descriptors to output

AIMS-202 Add description information to request display for batches

---

app/controllers/shelves_controller.rb
app/controllers/trays_controller.rb
app/views/shelves/missing.html.haml
config/locales/en.yml
config/routes.rb
spec/features/items_spec.rb

Improves the missing barcode message and fixes an error when trying to associate a not found item with a shelf.

AIMS-232 AIMS-240 Missing item messaging

---

Gemfile
Gemfile.lock

**What**: Upgraded the pg gem
**Why**: To use the latest gem, and make sure the driver is compatible with Postgres 9.4+

Upgrade the pg gem

---

app/assets/stylesheets/framework_and_overrides.css.scss
app/views/batches/index.html.haml
app/views/welcome/index.html.haml

Improved spacing around form elements as well as improved the home page interface to denote menu hierarchy.

Display corrections.

---

app/services/activity_logger.rb
app/services/api_post_deliver_item.rb
spec/services/activity_logger_spec.rb
spec/services/api_post_deliver_item_spec.rb

**What**: Added loggers for API scan/send ops
**How**: Added loggers to the activity logger class, added tests, and added log_activity method to api_post_deliver_item service class

AIMS-258, AIMS-259 Add activity loggers for api scan/send item

---

config/application.rb

Since we are using RSpec auto generate spec entries if a generator is
used.
[skip ci]

Updating application generator configuration

---

app/controllers/items_controller.rb
app/controllers/shelves_controller.rb
app/controllers/trays_controller.rb

Remove/change instances of "rescue StandardError"

---

Gemfile
Gemfile.lock
spec/models/tray_spec.rb

I had a question concerning whether or not a validation was missing. Since there is not a spec asserting whether validation is required or not, I didn't know.
Thoughts?

Adding shoulda matcher to convey intentionality

---

app/controllers/items_controller.rb
app/services/activity_logger.rb
app/services/add_issue.rb
app/services/resolve_issue.rb
spec/services/activity_logger_spec.rb
spec/services/resolve_issue_spec.rb

Log ResolvedIssue.  Also updated AddIssue to log the issue after it's saved (currently it's logging the issue record before it's created)

AIMS-273 Log ResolvedIssue.

---

app/controllers/items_controller.rb
app/queries/activity_log_query.rb
app/views/items/item_detail.html.haml
config/locales/en.yml
config/routes.rb
spec/features/items_spec.rb
spec/queries/activity_log_query_spec.rb

**What**: Added a first pass at an item detail page that will show current item information including status, the history of what has happened with the object at the Annex, and how often an item was requested and shipped/scanned.
**How**
* Added a new controller method and route
* Added a new query class for activity logs with item_history and item_usage methods
* Created the item detail page
* Added some i18n for activity messages
* Created appropriate unit tests

AIMS-107, AIMS-108, AIMS-109, AIMS-110 Add item detail page

---

app/views/batches/index.html.haml
app/views/batches/retrieve.html.haml
app/views/bins/show.html.haml
app/views/items/issues.html.haml
app/views/items/item_detail.html.haml
app/views/search/index.html.haml

**What**: Created links in the UI to the item detail page, and did a bug fix for the detail page itself
**How**: Just modified several views to include the link, and also put in a conditional for the tray barcode value to fix a bug.

AIMS-107, AIMS-279 Link to item detail page, and bug fix

---

app/controllers/application_controller.rb
app/controllers/simple_cas_controller.rb
app/controllers/users_controller.rb
app/views/users/index.html.haml
config/environments/development.rb
config/environments/pre_production.rb
config/environments/production.rb
config/environments/staging.rb
config/environments/test.rb
config/routes.rb
db/migrate/20150710142409_add_admin_to_users.rb
db/schema.rb
spec/controllers/application_controller_spec.rb
spec/controllers/batches_controller_spec.rb
spec/controllers/trays_controller_spec.rb
spec/controllers/users_controller_spec.rb
spec/support/authentication_helper.rb

Why: Need to restrict access to the application to a specified list of users
How: Added an admin field to the users table and modified the ApplicationController to check this. Essentially only administrators of the application will have any access, and they will all have access to a form to edit the users. In order to give permission to the first user you can configure an admin_user_name in the config.

AIMS-246: User access

---

app/views/items/item_detail.html.haml
config/settings.yml

**What**: Add link to catalog from item detail page
**How**: Added config to settings.yml for the catalog link, and added link to HAML page

AIMS-269 Add link to catalog from item details

---

app/services/external_rest_connection.rb

What: Just a minor code revision
Why: Addressing an ABC length issue for testing purposes
What: Shortened method and removed conditionals and several branch calls

AIMS-298 Minor cleanup

---

app/views/shelves/show.html.haml

What: Remove unstock button for item direct to shelf page
How: Just changed the show haml page

AIMS-293 Remove unstock button direct to shelf

---

app/queries/activity_log_query.rb

This is a redo of my last pull request

AIMS-297 Add conditions to item detail

---

Gemfile
Gemfile.lock
config/deploy.rb

This adds a maintenance page to public/system/maintenance.html during deployments.

Add a maintenance page during deploy

---

.travis.yml
spec/support/solr_spec_helper.rb

Travis Hipchat notifications: Notify a different room, only notify on build change, send an actual notification to the users in the room.
Solr: More time for solr to start in specs.

Travis Hipchat notification changes

---

app/controllers/transfers_controller.rb
spec/controllers/transfer_controller_spec.rb

**What**: Bug fix for shelf creation when transfer shelf target does not already exist.

AIMS-334 Bug fix for shelf creation on transfer

---

app/controllers/transfers_controller.rb
app/services/activity_logger.rb
spec/controllers/transfer_controller_spec.rb
spec/services/activity_logger_spec.rb

What:  Fixed a bug with the shelf parameter reference, and added new method for logging transfer destroy actions

AIMS-334 Bug fix and add activity logger for destroy shelf

---

app/controllers/transfers_controller.rb
app/services/destroy_request.rb
app/services/destroy_transfer.rb
app/views/transfers/view_active.html.haml
config/routes.rb
spec/controllers/transfer_controller_spec.rb
spec/services/destroy_transfer_spec.rb

What: Added service class for destroying transfers, added controller method for doing so, and added a date / time stamp to the active transfer list

AIMS-334 Add function to delete transfers, and add date/time to active transfer list

---

app/controllers/batches_controller.rb

AIMS-334 Reverting query to fix request bug

---

app/controllers/batches_controller.rb

What: Modified request query so that it excludes matches that were already created

AIMS-334 Simplify request query to exclude ALL match records

---

CHANGELOG.md

Made a changelog. It's super cool. Approve it. Do it.

AIMS-342: Changelog

---

app/models/batch.rb

What: Fixed a bug relating to determining unprocessed matches for a batch.

AIMS-343 Fixed criteria for determining unprocessed matches

---

app/controllers/application_controller.rb
app/controllers/batches_controller.rb
app/controllers/users_controller.rb
app/views/users/index.html.haml
app/views/welcome/index.html.haml
config/initializers/devise.rb
db/migrate/20160128174804_add_worker_column_to_users.rb
db/schema.rb
spec/controllers/application_controller_spec.rb
spec/controllers/batches_controller_spec.rb
spec/controllers/bins_controller_spec.rb
spec/controllers/trays_controller_spec.rb

I need a review of my code, to be more exact, I updated some controller files in Annex project, as well as wrote some spec unit testing. All changes were pushed already. I would like to see any feedback and suggestions.

Aims 335 add worker permissions

---

app/views/trays/show_item.html.haml

Now stocked items have barcodes with links to a page with a detailed information about items

AIMS-129: Stocked items have linked barcodes

---

app/views/batches/current.html.haml

If the item is added to the bin, then that item will have bin barcode presented instead of Remove button in View Current Batch page.

AIMS-344: Remove button is displayed only for items that have no bin barcode.

---

app/views/trays/show_item.html.haml

Added extra validation for thickness and updated fields to require values

AIMS-290: Add validation to item thickness field

---

app/controllers/trays_controller.rb
app/views/trays/show_item.html.haml

The way of calculating items in the tray was updated to more efficient way.
Also the indication of a number of items from show_item page removed.

AIMS-355: speeds up counting items in tray.

---

app/views/trays/show_item.html.haml

Added minimum value of 1 to avoid negative values to be entered.

AIMS-290: Updated input requirements to allow only positive values.

---

app/presenters/item_view_presenter.rb

Fixed the report to not append the "on issue list" text if all issues are resolved

Report resolved issues

---

app/views/deaccessioning/index.html.haml

AIMS-399 Require a reason

---

app/controllers/deaccessioning_controller.rb
app/controllers/requests_controller.rb
app/models/disposition.rb
app/models/item.rb
app/models/request.rb
app/services/activity_logger.rb
app/services/build_deaccessioning_request.rb
app/services/get_requests.rb
app/services/set_item_disposition.rb
app/views/deaccessioning/index.html.haml
db/migrate/20170515014300_add_disposition_and_comment_to_requests.rb
db/migrate/20170604211603_move_dispositions_from_requests_to_items.rb
db/schema.rb
spec/controllers/deaccessioning_controller_spec.rb
spec/services/activity_logger_spec.rb
spec/services/build_deaccessioning_request_spec.rb

Deaccessioning requests need to store comments and dispositions. This branch fixes that oversight.

Add comments and dispositions to requests

---

app/views/deaccessioning/index.html.haml
app/views/shared/_search_form.html.haml

It's a bit of a hack, but it works.

AIMS-396 remove export, move create request

---

app/controllers/deaccessioning_controller.rb
app/services/is_bin_barcode.rb
spec/controllers/deaccessioning_controller_spec.rb
spec/services/is_bin_barcode_spec.rb

For unstocked items, add them directly to a bin with a barcode of "BIN-DEAC-HAND-01".

Aims 403 deaccession unstocked

---

app/jobs/api_deaccession_item_job.rb
app/models/item.rb
app/services/activity_logger.rb
app/services/api_post_deaccession_item.rb
app/services/deaccession_item.rb
app/services/dissociate_item_from_bin.rb
app/services/is_deac_bin_barcode.rb
spec/factories/items.rb
spec/fixtures/api/deaccession_item.json
spec/jobs/api_deaccession_item_job_spec.rb
spec/services/activity_logger_spec.rb
spec/services/api_post_deaccession_item_spec.rb
spec/services/deaccession_item_spec.rb
spec/services/dissociate_item_from_bin_spec.rb
spec/services/is_deac_bin_barcode_spec.rb
spec/support/api_helper.rb

Making this call the API and doing it right involves quite a few ancilliary steps along the way.

AIMS-409 Call deaccessioning API

---

app/controllers/deaccessioning_controller.rb
app/views/deaccessioning/index.html.haml

This should preserve form values when no disposition is selected.

AIMS-399 Preserve form values.

---

app/controllers/dispositions_controller.rb

This should return to the list of dispositions when one is created.

AIMS-420 Return to list.

---

app/controllers/deaccessioning_controller.rb
spec/controllers/deaccessioning_controller_spec.rb

This should handle no items being selected.

AIMS-419 Handle no items

---

app/services/search_items.rb
app/views/shared/_search_form.html.haml

I'm not sure how to test this - again, it would be testing Sunspot/Solr.

AIMS-411 Allow search to return deaccessioned items.

---

app/controllers/update_controller.rb
app/views/welcome/index.html.haml
config/routes.rb
spec/controllers/update_controller_spec.rb
spec/features/update_spec.rb

This is based off 427 - that one should be reviewed and merged before this one, or this will pull that one in by default.

Aims 428 add update to menu

---

app/controllers/update_controller.rb
app/views/update/index.html.haml
app/views/welcome/index.html.haml
config/locales/en.yml
config/routes.rb
spec/controllers/update_controller_spec.rb
spec/features/update_spec.rb

This builds on 428, please review/merge that before this (and by extension 427 as well).

Aims 430 add verbiage to update page

---

app/controllers/update_controller.rb
app/views/update/_update_table.html.haml
app/views/update/index.html.haml
app/views/welcome/index.html.haml
config/locales/en.yml
config/routes.rb
spec/controllers/update_controller_spec.rb
spec/features/update_spec.rb

Builds on 430, please review/merge that first.

Aims 431 add barcode form

---

config/environments/development.rb
config/environments/pre_production.rb
config/environments/production.rb
config/environments/staging.rb

Change cas url

---

Gemfile

This is to resolve some issues we're having deploying from Jenkins

Grouping more dependencies into the application group

---

Gemfile
Gemfile.lock
app/controllers/update_controller.rb
app/models/request.rb
app/queries/activity_log_query.rb
app/services/deaccession_not_stocked_item.rb
app/services/is_bin_barcode.rb
app/services/is_deac_bin_barcode.rb
app/services/search_items.rb
app/views/update/show_existing.html.haml
config/locales/en.yml
config/routes.rb
spec/controllers/deaccessioning_controller_spec.rb
spec/features/update_spec.rb
spec/models/request_spec.rb
spec/services/dissociate_item_from_bin_spec.rb
spec/services/is_bin_barcode_spec.rb
spec/services/is_deac_bin_barcode_spec.rb

442 is also in this batch. Please review.
Please do not merge to master until we can deploy to the staging server.

Aims 446 448 449

---

app/services/build_deaccessioning_request.rb
spec/services/build_deaccessioning_request_spec.rb

Signed-off-by: Aaron F Stanton <afstanton@gmail.com>

AIMS-452 change DEACC to REMOVE in transaction

---

app/views/update/index.html.haml
app/views/update/show_old.html.haml
spec/features/update_spec.rb

Signed-off-by: Aaron F Stanton <afstanton@gmail.com>

AIMS-451 change Save to Go

---

Gemfile
Gemfile.lock
README.md
config/sunspot.yml

Also upgraded several other gems to remediate security vulnerabilities

Sunspot jetty upgrade

---

app/controllers/items_controller.rb
app/views/items/item_detail.html.haml
config/routes.rb
spec/controllers/items_controller_spec.rb

Added button for refreshing item, and tests for controller

AIMS-327-refresh-item 

---

app/views/search/index.html.haml

Add DataTable to search results page

AIMS-109-sort-search-results 

---

app/controllers/reporting_controller.rb
app/controllers/reports_controller.rb
app/models/report.rb
app/views/reporting/index.html.haml
app/views/reports/_form.html.haml
app/views/reports/_report.json.jbuilder
app/views/reports/edit.html.haml
app/views/reports/index.html.haml
app/views/reports/index.json.jbuilder
app/views/reports/new.html.haml
app/views/reports/show.html.haml
app/views/reports/show.json.jbuilder
app/views/welcome/index.html.haml
config/locales/en.yml
config/routes.rb
config/style_guides/.ruby-style.yml
db/migrate/20200302022638_create_reports.rb
db/schema.rb
spec/factories/reports.rb
spec/features/report_builder/report_builder_spec.rb
spec/models/report_spec.rb

Addresses AIMS 486, 487, 488 (kind of), 489 (kind of), 495, 496, 497, 498, 499. Does not address actually running the report. Minimal testing - more to be added.

Created this branch for a PR to split up some of the code.

---

app/controllers/reports_controller.rb
app/models/report.rb
app/services/build_report.rb
app/views/reports/_form.html.haml
app/views/reports/index.html.haml
app/views/reports/show.html.haml
app/views/welcome/index.html.haml
db/migrate/20210528161202_add_preset_date_range_to_report.rb
db/schema.rb
spec/services/build_report_spec.rb

This overrides start date and end date if those are also set. More ranges could easily be added. [AIMS-510]

Adds preset date ranges to the report builder.
